# Generated by Django 4.2.5 on 2023-09-06 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareacompletada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fechaCompletada', models.DateField()),
                ('estado', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=150)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
