# Generated by Django 4.2.5 on 2023-09-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSprint', '0002_tareacompletada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Alta', verbose_name='Prioridad'),
            preserve_default=False,
        ),
    ]
